#!/bin/bash

echo "🔍 VNET Access Troubleshooting Guide"
echo "====================================="
echo ""

VM_IP="20.220.23.102"
VNET_IP="207.219.79.126"

echo "VM IP: $VM_IP"
echo "VNET IP: $VNET_IP"
echo ""

# Step 1: Check if VNET IP is the actual source IP
echo "📋 STEP 1: Verify Source IP"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "❓ Question: Are you sure 207.219.79.126 is the actual PUBLIC IP"
echo "   that Azure sees when requests come from your VNET?"
echo ""
echo "🔧 How to verify:"
echo "   1. From a machine on your VNET, run:"
echo "      curl http://ifconfig.me"
echo ""
echo "   2. The IP returned is what you need to whitelist in Azure NSG"
echo ""
echo "⚠️  Common issue: The VNET might be using a NAT gateway or load balancer"
echo "   with a DIFFERENT public IP than you think!"
echo ""

# Step 2: Check Azure NSG
echo "📋 STEP 2: Check Azure NSG Configuration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run this command to see your current NSG rules:"
echo ""
echo "az network nsg rule list \\"
echo "  --resource-group YOUR-RESOURCE-GROUP \\"
echo "  --nsg-name YOUR-NSG-NAME \\"
echo "  --query \"[?destinationPortRange=='3000'].{Name:name, Source:sourceAddressPrefix, Priority:priority}\" \\"
echo "  --output table"
echo ""
echo "Look for:"
echo "  - Is Source set to 'Any' or '0.0.0.0/0'? (allows all IPs)"
echo "  - Is Source set to specific IPs? (might be blocking your VNET)"
echo ""

# Step 3: Test connectivity
echo "📋 STEP 3: Test Basic Connectivity"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "From a machine on your VNET (207.219.79.126), run these tests:"
echo ""
echo "# Test 1: Can you ping the VM?"
echo "ping -c 4 $VM_IP"
echo ""
echo "# Test 2: Can you reach port 3000?"
echo "telnet $VM_IP 3000"
echo "# Or use nc (netcat):"
echo "nc -zv $VM_IP 3000"
echo ""
echo "# Test 3: Try the actual API"
echo "curl -v http://$VM_IP:3000/api/health"
echo ""
echo "# Test 4: Check what your public IP is from VNET"
echo "curl http://ifconfig.me"
echo ""

# Step 4: Common issues
echo "📋 STEP 4: Common Issues & Solutions"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "❌ Issue 1: VNET is using different public IP"
echo "   Solution: Find actual public IP with 'curl ifconfig.me' from VNET"
echo "   Then whitelist THAT IP in Azure NSG"
echo ""
echo "❌ Issue 2: VNET firewall is blocking outbound traffic"
echo "   Solution: Check your corporate firewall/proxy settings"
echo "   Allow outbound traffic to $VM_IP:3000"
echo ""
echo "❌ Issue 3: Azure NSG priority conflict"
echo "   Solution: Make sure your allow rule has LOWER priority number"
echo "   than any deny rules (lower number = higher priority)"
echo ""
echo "❌ Issue 4: VM's internal firewall (UFW) is blocking"
echo "   Solution: On VM, check: sudo ufw status"
echo "   If active, allow port 3000: sudo ufw allow 3000/tcp"
echo ""
echo "❌ Issue 5: Wrong NSG attached to NIC"
echo "   Solution: Verify NSG is attached to VM's network interface"
echo ""

# Step 5: Temporary workaround
echo "📋 STEP 5: Temporary Workaround (Testing)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "To test if NSG is the issue, TEMPORARILY set Source to 'Any':"
echo ""
echo "1. Azure Portal → VM → Networking"
echo "2. Edit port 3000 rule"
echo "3. Set Source: Any"
echo "4. Save and test from VNET"
echo "5. If it works, NSG was blocking. Find correct IP and whitelist it."
echo "6. If it still doesn't work, issue is elsewhere (VNET firewall, routing, etc.)"
echo ""
echo "⚠️  Remember to change back from 'Any' to specific IPs for security!"
echo ""

# Step 6: Azure-specific checks
echo "📋 STEP 6: Azure-Specific Checks"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Check if VM has a public IP:"
echo "   az vm show -d -g YOUR-RG -n YOUR-VM --query publicIps -o tsv"
echo ""
echo "2. Check NSG associated with VM:"
echo "   az network nic show --ids \$(az vm show -g YOUR-RG -n YOUR-VM --query 'networkProfile.networkInterfaces[0].id' -o tsv) --query 'networkSecurityGroup.id' -o tsv"
echo ""
echo "3. Check effective security rules:"
echo "   az network nic list-effective-nsg -g YOUR-RG -n YOUR-NIC-NAME"
echo ""

# Step 7: What to share for help
echo "📋 STEP 7: Information to Gather"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Please gather this information:"
echo ""
echo "1. From VNET machine:"
echo "   curl http://ifconfig.me"
echo "   (This is your actual public IP)"
echo ""
echo "2. From VNET machine:"
echo "   curl -v http://$VM_IP:3000/api/health"
echo "   (Share the full error message)"
echo ""
echo "3. Ping test:"
echo "   ping -c 4 $VM_IP"
echo "   (Does it respond?)"
echo ""
echo "4. Port test:"
echo "   nc -zv $VM_IP 3000"
echo "   (Is port reachable?)"
echo ""
echo "5. Current NSG rules (run from Azure CLI or Cloud Shell):"
echo "   az network nsg rule list --resource-group YOUR-RG --nsg-name YOUR-NSG --output table"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Next Steps:"
echo "   1. Verify actual public IP from VNET: curl ifconfig.me"
echo "   2. Temporarily set NSG to 'Any' to test"
echo "   3. Check VNET's outbound firewall rules"
echo "   4. Share diagnostic output for further help"
echo ""
